# Generated by Django 3.2.8 on 2022-12-01 17:43

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("action_types", "0001_initial"),
        ("plants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("period", models.IntegerField(verbose_name="Period")),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("days", "Days"),
                            ("weeks", "Weeks"),
                            ("months", "Months"),
                            ("seasons", "Seasons"),
                            ("half_years", "Half years"),
                            ("year", "Years"),
                        ],
                        max_length=254,
                        verbose_name="Units",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=1024, verbose_name="Note"),
                ),
                (
                    "action_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="action_types.actiontype",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="plants.plant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule",
                "verbose_name_plural": "Schedules",
            },
        ),
    ]
